### ISSUE TITLE
Errors on import - Unable to add package

### ISSUE THREAD

**Issue by baroquedub** [VisualPinball/VisualPinball.Unity.Hdrp#2]
Using Unity 2020.2.1f1
Following the HDRP instructions from here: https://docs.visualpinball.org/creators-guide/setup/installing-vpe.html
I have VPE 0.0.1-preview.8 installed but when I try to install VisualPinball.Unity.Hdrp is get the following errors:
```
[Package Manager Window] Unable to add package [file:C:/Users/baroq/VPE/VisualPinball.Unity.Hdrp/VisualPinball.Unity.Hdrp-master]:
  Package org.visualpinball.engine.unity.hdrp@file:C:\Users\baroq\VPE\VisualPinball.Unity.Hdrp\VisualPinball.Unity.Hdrp-master has invalid dependencies or related test packages:
    org.visualpinball.unity.assetlibrary.hdrp (dependency): Package [org.visualpinball.unity.assetlibrary.hdrp@0.0.1-preview.6] cannot be found
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```
```
[Package Manager Window] Cannot perform upm operation: Unable to add package [file:C:/Users/baroq/VPE/VisualPinball.Unity.Hdrp/VisualPinball.Unity.Hdrp-master]:
  Package org.visualpinball.engine.unity.hdrp@file:C:\Users\baroq\VPE\VisualPinball.Unity.Hdrp\VisualPinball.Unity.Hdrp-master has invalid dependencies or related test packages:
    org.visualpinball.unity.assetlibrary.hdrp (dependency): Package [org.visualpinball.unity.assetlibrary.hdrp@0.0.1-preview.6] cannot be found [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```
```
[Package Manager Window] Error adding package: file:C:/Users/baroq/VPE/VisualPinball.Unity.Hdrp/VisualPinball.Unity.Hdrp-master.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```

**Comment by freezy** [comment]
Yeah sorry we're in the middle of changing the setup. If meanwhile you need a working setup, clone all the org's repos and add them as packages to your Unity project in this order:

1. [VisualPinball.Unity.AssetLibrary](https://github.com/VisualPinball/VisualPinball.Unity.AssetLibrary)
2. [VisualPinball.Unity.AssetLibrary.Hdrp](https://github.com/VisualPinball/VisualPinball.Unity.AssetLibrary.Hdrp)
3. [VisualPinball.Engine](https://github.com/freezy/VisualPinball.Engine)
4. [VisualPinball.Unity.Hdrp](https://github.com/VisualPinball/VisualPinball.Unity.Hdrp)

Going forward those will all be published on a scoped registry, so you'll just have to add one, or use the default project we will provide.

**Comment by baroquedub** [comment]
Thanks. I can comfirm that works.
Initially I got a bunch of errors after importing 'VisualPinball.Unity.AssetLibrary' (sorry didn't copy them). I just uninstalled the package and retried (pointing to the same unzipped folder and json file) and that time it worked without errors. Other package loaded just fine.

**Comment by freezy** [comment]
AssetLibrary uses git LFS, so if you pulled the zip, some files weren't included. git clone should work though.

**Comment by freezy** [comment]
Closing, this is now all [documented](https://docs.visualpinball.org/creators-guide/setup/installing-vpe.html#vpe-package).
